### ISSUE TITLE
Melhorar a descrição do jogo

### ISSUE THREAD

**Issue by MatheusFaria** [osbixaodaunb/RGBender#5]
Melhorem:
- a explicação os controles
- descrevam os membros do projeto e seus papéis
- dependencias e suas versões
- como perde e ganha
- genero do jogo
- O arquivo de licensas deve ser nomeado LICENSE (tá escrito errado atualmente)

**Comment by lopes05** [comment]
Corrigidos todos tópicos apontados.
Arquivo README atualizado.
